---
# tasks file for postfix
- name: Install postfix-packages
  ansible.builtin.apt:
    name: '{{ postfix_packages }}'
    state: present
    update_cache: true
  tags: [install]

- name: Configure main.cf
  ansible.builtin.template:
    src: '{{ postfix_main_tpl }}'
    dest: /etc/postfix/main.cf
    mode: '0644'
    owner: root
    group: root
  tags: [config]
  notify: Restart postfix

- name: Configure master.cf
  ansible.builtin.template:
    src: '{{ postfix_master_tpl }}'
    dest: /etc/postfix/master.cf
    mode: '0644'
    owner: root
    group: root
  tags: [config]
  notify: Restart postfix

- name: Configure sender login maps
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0644'
    owner: root
    group: root
  loop: '{{ postfix_sender_login_map_tpls }}'
  tags: [config]
  notify: Restart postfix

- name: Add server tls certificate
  ansible.builtin.copy:
    src: '{{ postfix_smtpd_tls_cert_src }}'
    dest: '{{ postfix_smtpd_tls_cert }}'
    owner: root
    group: root
    mode: '0644'
  when: postfix_smtpd_tls_cert_src is defined and postfix_smtpd_tls_cert_src
  notify: Restart postfix

- name: Add server tls certificate key
  ansible.builtin.copy:
    src: '{{ postfix_smtpd_tls_key_src }}'
    dest: '{{ postfix_smtpd_tls_key }}'
    owner: root
    group: root
    mode: '0600'
  when: postfix_smtpd_tls_key_src is defined and postfix_smtpd_tls_key_src
  notify: Restart postfix
