---
# tasks file for postfix
- name: install postfix-packages
  apt:
          name: "{{postfix_packages}}"
          state: present
          update_cache: yes
  tags: [install]


- name: configure main.cf
  template:
          src: "{{postfix_main_tpl}}"
          dest: "/etc/postfix/main.cf"
          mode: "0644"
          owner: "root"
          group: "root"
  tags: [config]
  notify: restart postfix


- name: configure master.cf
  template:
          src: "{{postfix_master_tpl}}"
          dest: "/etc/postfix/master.cf"
          mode: "0644"
          owner: "root"
          group: "root"
  tags: [config]
  notify: restart postfix


- name: Add server tls certificate
  copy:
    src: "{{ postfix_smtpd_tls_cert_src }}"
    dest: "{{ postfix_smtpd_tls_cert }}"
    owner: root
    group: root
    mode: "0644"
  when: postfix_smtpd_tls_cert_src is defined and postfix_smtpd_tls_cert_src
  notify: restart postfix

- name: Add server tls certificate key
  copy:
    src: "{{ postfix_smtpd_tls_key_src }}"
    dest: "{{ postfix_smtpd_tls_key }}"
    owner: root
    group: root
    mode: "0600"
  when: postfix_smtpd_tls_key_src is defined and postfix_smtpd_tls_key_src
  notify: restart postfix